config/routes.rb
Rails.application.routes.draw do

  root 'movies#index'

  resources :movies do 
    resources :reviews, except: [:index]
  end

  resources :reviews, only: [:index]

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews

	validates :title, presence: true


	def self.search(search)
	  if search
	    where('title LIKE ?', "%#{search}%")
	  else
	    self.all
	  end
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie

	validates :movie, presence: true
	validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	helper_method :sort_column, :sort_direction

	def index
		@movies = Movie.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
	end

	def show
		@movie = Movie.find(params[:id])
	end

	private

	def sort_column
		Movie.column_names.include?(params[:sort]) ? params[:sort] : "title"
	end

	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	require 'segment/analytics'

	def index
		@reviews = Review.all
	end

	def new
		@review = Review.new(movie_id: params[:movie_id])
	end

	def create
		@review = Review.new(review_params)
		Analytics.identify(
	    user_id: SecureRandom.uuid,
	    traits: {
	      email: params[:review][:email],
	      created_at: DateTime.now
	    })

		Analytics.track(
    user_id: SecureRandom.uuid,
    event: 'Movie Review',
    properties: {
      movie_id: params[:movie_id],
      email: params[:review][:email],
      comment: params[:review][:comment]
    })

		if @review.save
			flash[:success] = "You've reviewed #{@review.movie.title}, go review again!"
			redirect_to movies_path
		else
			render :new
		end
	end

	def show
	end

private
	
	def review_params
		params.require(:review).permit(:email, :rating, :comment, :movie_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, params.merge(:sort=> column, :direction => direction, :page => nil)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "The Reel Scoop", root_path, class: "navbar-brand" %>
        </div>
      </div>
    </nav>
<div class="container">

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>


<%= debug(params) if Rails.env.development? %>

<%= yield %>

</div>
</body>
</html>

app/views/movies/_movies.html.erb
<table class="table table-striped">
    <tr>
      <th><%= sortable "title" %></th>
      <th><%= sortable "release_date" %></th>
      <th><%= sortable "genres" %></th>
      <th></th>
     </tr>
	<% @movies.each do |movie| %>
    <tr>
      <td> <%= link_to(image_tag(movie.mob_poster_url), new_movie_review_path(movie) )%> <%=link_to(movie.title, new_movie_review_path(movie))%> </td>
      <td> <%= movie.release_date.strftime("%B %e, %Y") %> </td>
      <td> <%= movie.genres %> </td>
      <td> <%= link_to("Show Reviews", movie_path(movie))%> | <%= link_to("Review Movie", new_movie_review_path(movie))%> </td>
    </tr>
    <% end %>
  </table>

app/views/movies/index.html.erb
<h3>Movies</h3>

<%= form_tag movies_path, :method => 'get', :id => "movies_search" do %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :title => nil %>
  </p>
<% end %>

<%= link_to "ALL REVIEWS", reviews_path %> 
  <div id='movies'> <%= render partial: 'movies' %> </div>

  <%= will_paginate @movies %> 

app/views/movies/index.js.erb
$("#movies").html("<%= escape_javascript(render :partial => "movies" ) %>");

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<table class="table table-striped">
    <tr>
      <th> Reviewer Email </th>
      <th> Rating (out of 5)</th>
      <th> Comment</th>
    </tr>
	<% @movie.reviews.each do |movie_review| %>
    <tr>
      <td> 	<%= movie_review.email %></td>
      <td> 	<%= movie_review.rating %> out of 5 </td>
      <td>  <%= movie_review.comment if movie_review.comment.present? %> </td>
    </tr>
    <% end %>
</table>

app/views/reviews/index.html.erb
<table class="table table-striped">
    <tr>
      <th> Movie </th>
      <th> Reviewer Email </th>
      <th> Rating </th>
      <th> Comment</th>
    </tr>
	<% @reviews.each do |review| %>
    <tr>  
      <td>  <%= link_to(review.movie.title, movie_path(review.movie)) %></td>
      <td> 	<%= review.email %></td>
      <td> 	<%= review.rating %> </td>
      <td>  <%= review.comment if review.comment.present? %> </td>
    </tr>
    <% end %>
</table>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
  <%= @review.errors.count %> Error(s) Prevented the Review from Saving
  <ul>
    <% @review.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>
<h1> Rate this Movie! </h1>

<%= image_tag(@review.movie.mob_poster_url) %><br>
<%= @review.movie.title %>

<ul>
<%= form_for [@review.movie, @review], html: {class: "form-horizontal"} do |f| %>
<li>
	<%= f.hidden_field :movie_id %>
	<%= f.label :email %>
	<li><%= f.text_field :email, class: "form-control-sm", placeholder: "Email" %><br>
	<span>Rating</span>
	<%= f.radio_button :rating, 1 %>
	<%= f.label :rating, value: 1 %>
	<%= f.radio_button :rating, 2 %>
	<%= f.label :rating, value: 2 %>
	<%= f.radio_button :rating, 3 %>
	<%= f.label :rating, value: 3 %>
	<%= f.radio_button :rating, 4 %>
	<%= f.label :rating, value: 4 %>

	<li><%=f.label :comment, raw('Comment <span>(optional)</span>') %>
	<li><%=f.text_area :comment,  class: "form-control" %>

	<li><%=f.submit "Submit Review", class: "btn btn-success" %>

<% end %> 
</ul>